name: cargo-about
description: "Performs a cargo about generation"

inputs:
  output-file:
    required: true
    description: "The output file name"

runs:
  using: "composite"
  steps:
    - name: Install cargo-about
      uses: ./.github/actions/cargo-install
      with:
        target: cargo-about

    - name: Generate license manifest
      shell: bash
      run: |
        cargo about generate                                                   \
          --all-features                                                       \
          --output-file ${{ inputs.output-file }}                              \
          --config .cargo-about/about.toml                                     \
          .cargo-about/template.hbs
