[package]
name = "alloy"
version.workspace = true
authors.workspace = true
categories.workspace = true
license.workspace = true
keywords.workspace = true
repository.workspace = true
edition.workspace = true

[features]
default = ["vulkan", "openal"]
vulkan = []
opengl = []
openal = []

[dependencies]
glfw = { path = "frameworks/glfw" }
vulkan = { path = "frameworks/vulkan", optional = true }
openal = { path = "frameworks/openal", optional = true }
