name: rust
description: "Install Rust toolchain, with caching"

inputs:
  rust:
    required: false
    description: "Rust toolchain, e.g. 'stable' or 'nightly'"
    default: stable
  cache-key:
    required: false
    description: "Key to resolve rust-cache"
    default: ''
  components:
    required: false
    description: "Additional components to install, separated by spaces. e.g. 'clippy', 'rustfmt', etc."
    default: ''

runs:
  using: "composite"
  steps:
    - name: Install Rust Toolchain
      shell: bash
      run: |
        rustup toolchain install ${{ inputs.rust }} --profile minimal --no-self-update
        rustup default ${{ inputs.rust }}

    - name: Install Rust Components
      shell: bash
      if: inputs.components != ''
      run: |
        rustup component add ${{ inputs.components }}

    - name: Prepare Cache
      uses: Swatinem/rust-cache@v2
      with:
        shared-key: ${{ inputs.cache-key }}

    - name: Prepare Rust Toolchain
      shell: bash
      run: |
        echo CARGO_TERM_COLOR=always >> ${GITHUB_ENV}
        echo CARGO_INCREMENTAL=0 >> ${GITHUB_ENV}
        echo RUST_BACKTRACE=1 >> ${GITHUB_ENV}

        rustc --version --verbose
