# Schema: https://doc.rust-lang.org/cargo/reference/manifest.html
[package]
name = "foundation"
version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
categories = []
keywords = []
edition.workspace = true

[dependencies]
uuid = "1.6.1"
