name: github-close-pr
description: "A tool for automatically closing pull requests"

runs:
  using: "composite"
  steps:
    - name: Leave Issue or Pull Request comment
      uses: actions/github-script@v7
      with:
        retries: 3
        script: |
          github.rest.pulls.update({
            pull_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            state: 'closed'
          });
