blank_issues_enabled: false
contact_links:
  - name: ❓ Ask a question about this project
    url: https://github.com/bitwizeshift/alloy-rs/discussions/categories/q-a
    about: Please ask and/or answer questions about this project here.
