name: Security Vulnerability report
description: 🔐 File a Security Vulnerability report
title: "[Security]: "
labels: ["security", "triage"]
assignees:
  - bitwizeshift
body:
  - type: markdown
    attributes:
      value: Thank you for taking the time to fill out this vulnerability report!
  - type: dropdown
    id: systems
    attributes:
      label: What systems are affected by this vulnerability?
      multiple: true
      options:
        - macOS
        - Windows
        - Linux
  - type: textarea
    id: what-vulnerability
    attributes:
      label: What is the vulnerability you discvoered?
      description: Please describe what the vulnerability is
      placeholder: What did you experience?
    validations:
      required: true
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: How do you trigger this vulnerability? Please walk us through it step by step.
      placeholder: |
        1.
        2.
        3.
        ...
      render: bash
  - type: textarea
    id: vulnerability-description
    attributes:
      label: How might this vulnerability be applied?
      description: |
        Please describe how a bad-actor might leverage this vulnerability.
        What is the worst-case scenario?
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: |
        Please copy and paste any relevant log output.
        This will be automatically formatted into code, so no need for backticks.
      render: raw
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](../CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true

