name: cargo-install
description: "Performs a cargo install for the specified component, with caching"

inputs:
  target:
    required: true
    description: "The component to install"
  git-repo:
    required: false
    description: "The git repo address to install"
    default: ""

runs:
  using: "composite"
  steps:
    - name: Cache installation
      id: cargo-install
      uses: actions/cache@v4
      with:
        path: .cargo/bin/${{ inputs.target }}
        key: cargo-install-${{ runner.os }}-${{ inputs.target }}

    - name: Install cargo binary
      if: steps.cargo-install.outputs.cache-hit != 'true'
      shell: bash
      env:
        CARGO_NET_GIT_FETCH_WITH_CLI: "true"
      run: |
        remaining="--git ${{ inputs.git-repo }}"
        if [[ -z "${{ inputs.git-repo }}" ]]; then
          remaining="--locked ${{ inputs.target }}"
        fi

        mkdir -p .cargo/bin
        cargo install                                                          \
          --root ./.cargo                                                      \
          ${remaining}

    - name: Update PATH
      shell: bash
      run: |
        echo "$(pwd)/.cargo/bin" >> "${GITHUB_PATH}"
