# Schema: https://doc.rust-lang.org/cargo/reference/manifest.html
[package]
name = "gl-sys"
version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
edition.workspace = true

[dependencies]
glew-sys = { path = "../glew-sys" }
