name: github-comment
description: "A tool for commenting on a Github issue or pull request"

inputs:
  message:
    required: true
    description: "The message to comment"
  retries:
    required: false
    default: "3"
    description: "The number of times to try retrying"
  retry-exempt-status-codes:
    required: false
    default: "400,401,403,404,422"
    description: "The retry exempt status codes"

runs:
  using: "composite"
  steps:
    - name: Leave Issue or Pull Request comment
      uses: actions/github-script@v7
      with:
        retries: ${{ inputs.retries }}
        retry-exempt-status-codes: ${{ inputs.retry-exempt-status-codes }}
        script: |
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: `${{ inputs.message }}`
          })
