name: cargo-build
description: "Performs a cargo build, with caching"

runs:
  using: "composite"
  steps:
    - name: Cache installation
      id: cargo-install-gh-annotation
      uses: actions/cache@v3
      with:
        path: .cargo/bin/cargo-github-annotation
        key: cargo-install-cargo-github-annotation

    - name: Install cargo-github-annotation
      if: steps.cargo-install-gh-annotation.outputs.cache-hit != 'true'
      env:
        CARGO_NET_GIT_FETCH_WITH_CLI: "true"
      shell: bash
      run: |
        cargo install                                                          \
          --root ./.cargo                                                      \
          --git https://github.com/bitwizeshift/cargo-github-annotation

    - name: Update PATH
      shell: bash
      run: |
        echo "$(pwd)/.cargo/bin" >> "${GITHUB_PATH}"

    - name: Cache build
      id: cargo-build
      uses: actions/cache@v3
      with:
        path: target
        key: cargo-build-${{ runner.os }}-${{ hashFiles('frameworks/**/*.rs', 'alloy/**/*.rs', 'example/**/*.rs', '**/Cargo.toml', 'Cargo.toml') }}

    - name: Build
      if: steps.cargo-build.outputs.cache-hit != 'true'
      shell: bash
      run: |
        cargo build --verbose --message-format json                            \
          | cargo-github-annotation
