name: cargo-build
description: "Performs a cargo build, with caching"

runs:
  using: "composite"
  steps:
    - name: Cache build
      id: cargo-build
      uses: actions/cache@v3
      with:
        path: target
        key: cargo-build-${{ runner.os }}-${{ hashFiles('frameworks/**/*.rs', 'alloy/**/*.rs', 'example/**/*.rs', '**/Cargo.toml', 'Cargo.toml') }}

    - name: Build
      if: steps.cargo-build.outputs.cache-hit != 'true'
      shell: bash
      run: |
        cargo build --verbose
