name: cargo-build
description: "Performs a cargo build, with caching"
inputs:
  profile:
    default: dev
    description: "The build profile to use"
    required: false

runs:
  using: "composite"
  steps:
    - name: Install markdownlint-github-annotation
      uses: ./.github/actions/cargo-install
      with:
        target: cargo-github-annotation
        git-repo: https://github.com/bitwizeshift/cargo-github-annotation

    - name: Cache build
      id: cargo-build
      uses: actions/cache@v3
      with:
        path: target
        key: cargo-build-${{ inputs.profile }}-${{ runner.os }}-${{ hashFiles('frameworks/**/*.rs', 'alloy/**/*.rs', 'example/**/*.rs', '**/Cargo.toml', 'Cargo.toml') }}

    - name: Build
      if: steps.cargo-build.outputs.cache-hit != 'true'
      shell: bash
      run: |
        cargo build                                                            \
          --verbose                                                            \
          --profile ${{ inputs.profile }}                                      \
          --message-format json                                                \
          | cargo-github-annotation
