# Schema: https://doc.rust-lang.org/cargo/reference/manifest.html
[package]
name = "gl"
version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
edition.workspace = true

[dependencies]
gl-sys = { path = "../gl-sys" }
