[book]
authors = ["Matthew Rodusek"]
language = "en"
multilingual = false
src = "src"
title = "Alloy Game Engine (Rust)"

[preprocessor.mermaid]
command = "mdbook-mermaid"

[output.html]
additional-js = ["mermaid.min.js", "mermaid-init.js"]
