name: prepare-runner
description: "Prepares the underlying runner for building this project"

runs:
  using: "composite"
  steps:
    - name: Setup Clang
      uses: ./.github/actions/setup-clang

    - name: Update package cache
      uses: ./.github/actions/update-apt

    - name: Setup OpenAL Soft
      uses: ./.github/actions/setup-openal-soft

    - name: Setup GLFW
      uses: ./.github/actions/setup-glfw

    - name: Setup Boxer
      uses: ./.github/actions/setup-boxer

    - name: Setup Vulkan
      uses: ./.github/actions/setup-vulkan

    - name: Checkout 3rd-party
      uses: ./.github/actions/checkout
