name: Audit
on:
  push:
    branches: [master]
  schedule: [cron: "0 0 * * 0"]
  workflow_call:

jobs:
  format:
    name: Audit packages
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install toolchain
        uses: ./.github/actions/rust-toolchain
        with:
          components: rustfmt

      - name: Install cargo-audit
        uses: ./.github/actions/cargo-install
        with:
          target: cargo-audit

      - name: Audit packages
        run: cargo audit
