name: Build and Test
on:
  workflow_call:

jobs:
  build:
    name: Build and Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          # - macos-latest
          # - windows-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Clang
        uses: ./.github/actions/setup-clang

      - name: Update package cache
        uses: ./.github/actions/update-apt

      - name: Setup OpenAL Soft
        uses: ./.github/actions/setup-openal-soft

      - name: Setup GLFW
        uses: ./.github/actions/setup-glfw

      - name: Setup Boxer
        uses: ./.github/actions/setup-boxer

      - name: Setup Vulkan
        uses: ./.github/actions/setup-vulkan

      - name: Checkout 3rd-party
        uses: ./.github/actions/checkout

      - name: Install toolchain
        uses: ./.github/actions/rust-toolchain
        with:
          components: llvm-tools-preview

      - name: Build
        id: build
        uses: ./.github/actions/cargo-build

      - name: Test
        id: test
        run: cargo test --verbose

      - name: Doctest
        run: cargo test --doc --verbose

      - name: Coverage
        uses: ./.github/actions/cargo-code-coverage
        with:
          output-file: ${{ matrix.os }}-codecov.json
          minimum-requirement: 0.0
