name: Bundle Binaries
on:
  workflow_run:
    workflows: [ build ]
    types:
      - completed
  workflow_dispatch:
    inputs:
      profile:
        description: "The build profile to use"
        required: false
        default: dev
        options:
          - dev
          - release
        type: choice
  workflow_call:
    inputs:
      profile:
        description: "The build profile to use"
        default: dev
        required: false
        type: string

jobs:
  example-app-macos:
    name: Bundle MacOS Binary
    runs-on: macos-latest
    if: ${{ github.event_name != 'workflow_run' || github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare runner
        uses: ./.github/actions/prepare-runner

      - name: Install toolchain
        uses: ./.github/actions/rust-toolchain

      - name: Select profile
        id: select
        run: |
          if [[ -z "${{ inputs.profile }}" ]]; then
            echo "profile=dev" >> "${GITHUB_OUTPUT}"
          else
            echo "profile=${{ inputs.profile }}" >> "${GITHUB_OUTPUT}"
          fi

      - name: Build
        uses: ./.github/actions/cargo-build
        with:
          profile: ${{ steps.select.outputs.profile }}

      - name: Bundle
        uses: ./.github/actions/cargo-bundle
        with:
          profile: ${{ steps.select.outputs.profile }}
          path: example
