name: Label issues
on:
  issues:
    types: [opened, reopened]

jobs:
  run:
    name: Label github issue
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Get issue
        uses: bitwizeshift/actions-github/issues/get@v1
        id: issue
      - name: Add assignee
        if: ${{ !contains(steps.issue.outputs.assignees, 'bitwizeshift') }}
        uses: bitwizeshift/actions-github/issues/add-assignees@v1
        with:
          assignees: bitwizeshift
      - name: Add labels
        if: ${{ !contains(steps.issue.outputs.labels, 'triaged') }}
        uses: bitwizeshift/actions-github/issues/add-labels@v1
        with:
          labels: triage-required
