name: Deploy Github Pages
on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  generate:
    name: Generate cargo docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install toolchain
        uses: ./.github/actions/rust-toolchain
        with:
          rust: nightly

      - name: Install mdbook
        run: |
          cargo install --locked mdbook

      - name: Install cargo-llvm-cov
        uses: taiki-e/install-action@cargo-llvm-cov

      - name: Generate Book
        run: |
          mdbook build docs
          mkdir -p target/doc
          cp -r docs/book target/doc/book

      - name: Generate Cargo Docs
        run: |
          RUSTDOCFLAGS="--enable-index-page -Zunstable-options" \
          cargo +nightly doc --no-deps --workspace

      - name: Generate coverage report
        run: |
          cargo llvm-cov --html
          cp -r target/llvm-cov/html target/doc/coverage

      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./target/doc

  deploy:
    name: Deploy to GH Pages
    runs-on: ubuntu-latest
    needs: generate

    permissions:
      contents: read
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Upload GH Pages
        id: deployment
        uses: actions/deploy-pages@v1
